version: '3.0'

expectations:
  population_size: 10000

actions:

  # Extract data
  generate_study_population_wave4:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_wave4
        --skip-existing
        --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_wave4.csv.gz

  # Process data
  process_data_wave4:
    run: r:latest analysis/data_process.R wave4
    needs: [generate_study_population_wave4]
    outputs:
      highly_sensitive:
        rds: output/processed/input_wave4.rds
        
  # Skim data
  skim_data_wave4:
    run: r:latest analysis/data_skim.R output/processed/input_wave4.rds output/data_properties
    needs: [process_data_wave4]
    outputs:
      moderately_sensitive:
        txt1: output/data_properties/input_wave4_skim.txt
        txt2: output/data_properties/input_wave4_coltypes.txt
        txt3: output/data_properties/input_wave4_tabulate.txt
        
  # Filter data
  filter_data_wave4:
    run: r:latest analysis/data_selection.R wave4
    needs: [process_data_wave4]
    outputs:
      highly_sensitive:
        rds: output/filtered/input_wave4.rds
      moderately_sensitive:
        csv: output/flowchart/flowchart_wave4.csv

  # Immunosuppression combinations
  imm_comb_wave4:
    run: r:latest analysis/imm_comb.R wave4
    needs: [filter_data_wave4]
    outputs:
      moderately_sensitive:
        csv1: output/imm_comb/imm_comb_wave4_broad.csv
        csv2: output/imm_comb/imm_comb_wave4_narrow.csv

  # Table 1
  table_1_wave4_all:
    run: r:latest analysis/table_1.R wave4 all
    needs: [filter_data_wave4]
    outputs:
      highly_sensitive:
        data: output/table_1/table_1_wave4_all.rds
      moderately_sensitive:
        table: output/table_1/table_1_wave4_all.html
        csv: output/table_1/table_1_wave4_all.csv
        
  table_1_wave4_Tx:
    run: r:latest analysis/table_1.R wave4 Tx
    needs: [filter_data_wave4]
    outputs:
      highly_sensitive:
        data: output/table_1/table_1_wave4_Tx.rds
      moderately_sensitive:
        table: output/table_1/table_1_wave4_Tx.html
        csv: output/table_1/table_1_wave4_Tx.csv

  table_1_wave4_HC:
    run: r:latest analysis/table_1.R wave4 HC
    needs: [filter_data_wave4]
    outputs:
      highly_sensitive:
        data: output/table_1/table_1_wave4_HC.rds
      moderately_sensitive:
        table: output/table_1/table_1_wave4_HC.html
        csv: output/table_1/table_1_wave4_HC.csv

  table_1_wave4_RC:
    run: r:latest analysis/table_1.R wave4 RC
    needs: [filter_data_wave4]
    outputs:
      highly_sensitive:
        data: output/table_1/table_1_wave4_RC.rds
      moderately_sensitive:
        table: output/table_1/table_1_wave4_RC.html
        csv: output/table_1/table_1_wave4_RC.csv
        
  table_1_wave4_IMM:
    run: r:latest analysis/table_1.R wave4 IMM
    needs: [filter_data_wave4]
    outputs:
      highly_sensitive:
        data: output/table_1/table_1_wave4_IMM.rds
      moderately_sensitive:
        table: output/table_1/table_1_wave4_IMM.html
        csv: output/table_1/table_1_wave4_IMM.csv

  table_1_wave4_IMD:
    run: r:latest analysis/table_1.R wave4 IMD
    needs: [filter_data_wave4]
    outputs:
      highly_sensitive:
        data: output/table_1/table_1_wave4_IMD.rds
      moderately_sensitive:
        table: output/table_1/table_1_wave4_IMD.html
        csv: output/table_1/table_1_wave4_IMD.csv



  # Table - incidence rates
  table_ir_wave4_Tx:
    run: r:latest analysis/table_ir.R wave4 Tx
    needs: [filter_data_wave4]
    outputs:
      moderately_sensitive:
        csv: output/table_ir/table_ir_wave4_Tx.csv

  table_ir_wave4_HC:
    run: r:latest analysis/table_ir.R wave4 HC
    needs: [filter_data_wave4]
    outputs:
      moderately_sensitive:
        csv: output/table_ir/table_ir_wave4_HC.csv

  table_ir_wave4_RC:
    run: r:latest analysis/table_ir.R wave4 RC
    needs: [filter_data_wave4]
    outputs:
      moderately_sensitive:
        csv: output/table_ir/table_ir_wave4_RC.csv
        
  table_ir_wave4_IMM:
    run: r:latest analysis/table_ir.R wave4 IMM
    needs: [filter_data_wave4]
    outputs:
      moderately_sensitive:
        csv: output/table_ir/table_ir_wave4_IMM.csv

  table_ir_wave4_IMD:
    run: r:latest analysis/table_ir.R wave4 IMD
    needs: [filter_data_wave4]
    outputs:
      moderately_sensitive:
        csv: output/table_ir/table_ir_wave4_IMD.csv


