version: '3.0'

expectations:
  population_size: 10000

actions:

  # Extract data
  generate_study_population_wave4:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_wave4
        --skip-existing
        --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_wave4.csv.gz

  # Process data
  process_data_wave4:
    run: r:latest analysis/data_process.R wave4
    needs: [generate_study_population_wave4]
    outputs:
      highly_sensitive:
        rds: output/processed/input_wave4.rds
        
  # Skim data
  skim_data_wave4:
    run: r:latest analysis/data_skim.R output/processed/input_wave4.rds output/data_properties
    needs: [process_data_wave4]
    outputs:
      moderately_sensitive:
        txt1: output/data_properties/input_wave4_skim.txt
        txt2: output/data_properties/input_wave4_coltypes.txt
        txt3: output/data_properties/input_wave4_tabulate.txt
        
  # Filter data
  filter_data_wave4:
    run: r:latest analysis/data_selection.R wave4
    needs: [process_data_wave4]
    outputs:
      highly_sensitive:
        rds: output/filtered/input_wave4.rds
      moderately_sensitive:
        csv: output/flowchart/flowchart_wave4.csv

  # Table 1
  table_1_wave4_all:
    run: r:latest analysis/table_1.R wave4 all
    needs: [filter_data_wave4]
    outputs:
      highly_sensitive:
        data: output/table_1/table_1_wave4_all.rds
      moderately_sensitive:
        table: output/table_1/table_1_wave4_all.html
        csv: output/table_1/table_1_wave4_all.csv
        
  table_1_wave4_transplant:
    run: r:latest analysis/table_1.R wave4 transplant
    needs: [filter_data_wave4]
    outputs:
      highly_sensitive:
        data: output/table_1/table_1_wave4_transplant.rds
      moderately_sensitive:
        table: output/table_1/table_1_wave4_transplant.html
        csv: output/table_1/table_1_wave4_transplant.csv

  table_1_wave4_haem_cancer:
    run: r:latest analysis/table_1.R wave4 haem_cancer
    needs: [filter_data_wave4]
    outputs:
      highly_sensitive:
        data: output/table_1/table_1_wave4_haem_cancer.rds
      moderately_sensitive:
        table: output/table_1/table_1_wave4_haem_cancer.html
        csv: output/table_1/table_1_wave4_haem_cancer.csv

  table_1_wave4_imm:
    run: r:latest analysis/table_1.R wave4 imm
    needs: [filter_data_wave4]
    outputs:
      highly_sensitive:
        data: output/table_1/table_1_wave4_imm.rds
      moderately_sensitive:
        table: output/table_1/table_1_wave4_imm.html
        csv: output/table_1/table_1_wave4_imm.csv

  table_1_wave4_imd:
    run: r:latest analysis/table_1.R wave4 imd
    needs: [filter_data_wave4]
    outputs:
      highly_sensitive:
        data: output/table_1/table_1_wave4_imd.rds
      moderately_sensitive:
        table: output/table_1/table_1_wave4_imd.html
        csv: output/table_1/table_1_wave4_imd.csv

  table_1_wave4_radio_chemo:
    run: r:latest analysis/table_1.R wave4 radio_chemo
    needs: [filter_data_wave4]
    outputs:
      highly_sensitive:
        data: output/table_1/table_1_wave4_radio_chemo.rds
      moderately_sensitive:
        table: output/table_1/table_1_wave4_radio_chemo.html
        csv: output/table_1/table_1_wave4_radio_chemo.csv

  # Table - incidence rates
  table_ir_wave4_transplant:
    run: r:latest analysis/table_ir.R wave4 transplant
    needs: [filter_data_wave4]
    outputs:
      moderately_sensitive:
        csv: output/table_ir/table_ir_wave4_transplant.csv

  table_ir_wave4_haem_cancer:
    run: r:latest analysis/table_ir.R wave4 haem_cancer
    needs: [filter_data_wave4]
    outputs:
      moderately_sensitive:
        csv: output/table_ir/table_ir_wave4_haem_cancer.csv

  table_ir_wave4_imm:
    run: r:latest analysis/table_ir.R wave4 imm
    needs: [filter_data_wave4]
    outputs:
      moderately_sensitive:
        csv: output/table_ir/table_ir_wave4_imm.csv

  table_ir_wave4_imd:
    run: r:latest analysis/table_ir.R wave4 imd
    needs: [filter_data_wave4]
    outputs:
      moderately_sensitive:
        csv: output/table_ir/table_ir_wave4_imd.csv

  table_ir_wave4_radio_chemo:
    run: r:latest analysis/table_ir.R wave4 radio_chemo
    needs: [filter_data_wave4]
    outputs:
      moderately_sensitive:
        csv: output/table_ir/table_ir_wave4_radio_chemo.csv
